// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfif_1bVpttK1oVRvrnIQn-QidKTm_aH4',
    appId: '1:988284952137:web:7549de9ebe1da1e636a998',
    messagingSenderId: '988284952137',
    projectId: 'ai-agents-auth',
    authDomain: 'ai-agents-auth.firebaseapp.com',
    storageBucket: 'ai-agents-auth.firebasestorage.app',
    measurementId: 'G-Y6ZPKJ8ZE7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyBfNxiK8CAJy5QZzJAFPljMRTUFN4Q48',
    appId: '1:988284952137:android:ca34788c164d7d7a36a998',
    messagingSenderId: '988284952137',
    projectId: 'ai-agents-auth',
    storageBucket: 'ai-agents-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6etFPhLJUOcXLbW-X_sin2GYXDK-9xDU',
    appId: '1:988284952137:ios:e7369c03b87dac0f36a998',
    messagingSenderId: '988284952137',
    projectId: 'ai-agents-auth',
    storageBucket: 'ai-agents-auth.firebasestorage.app',
    iosClientId: '988284952137-n7dr7qc6ds1sapvg2gv36aa0vklkid14.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiAgentsUi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6etFPhLJUOcXLbW-X_sin2GYXDK-9xDU',
    appId: '1:988284952137:ios:e7369c03b87dac0f36a998',
    messagingSenderId: '988284952137',
    projectId: 'ai-agents-auth',
    storageBucket: 'ai-agents-auth.firebasestorage.app',
    iosClientId: '988284952137-n7dr7qc6ds1sapvg2gv36aa0vklkid14.apps.googleusercontent.com',
    iosBundleId: 'com.example.aiAgentsUi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfif_1bVpttK1oVRvrnIQn-QidKTm_aH4',
    appId: '1:988284952137:web:7549de9ebe1da1e636a998',
    messagingSenderId: '988284952137',
    projectId: 'ai-agents-auth',
    authDomain: 'ai-agents-auth.firebaseapp.com',
    storageBucket: 'ai-agents-auth.firebasestorage.app',
    measurementId: 'G-Y6ZPKJ8ZE7',
  );

}